apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-app
  labels:
    frontendapp: shoppingwebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      frontendapp: shoppingwebapp
  template:
    metadata:
      labels:
        frontendapp: shoppingwebapp
    spec:
      containers:
        - name: shopping-app-container
          image: IMAGE_VALUE
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: API_URL
              value: "http://shopping-server-service:5135"

---
apiVersion: v1
kind: Service
metadata:
  name: shopping-app-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    frontendapp: shoppingwebapp
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
